application: davide-ceretti
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: core.app.application

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6
